services:
  hoyodecrimen:
    container_name: hoyodecrimen
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      MODULE_NAME: "${MODULE_NAME}"
      LOG_LEVEL: "${LOG_LEVEL}"
      PORT: "${PORT}"
      SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
      PRODUCTION: "True"
      #SENTRY_DSN: "${SENTRY_DNS}"
      CACHE_SECRET: "${CACHE_SECRET}"
    image: diegovalle/hoyodecrimen
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 180s
      timeout: 30s
      retries: 7
    user: "1000:1000"
    # volumes:
    #   - /hoyodecrimen/wsgi/static/.webassets-cache:/app/static/.webassets-cache
    #   - /hoyodecrimen/wsgi/static/gen:/app/static/gen
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - .env

  db:
    container_name: hoyodecrimen-postgis
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      HOYODECRIMEN_BACKUP_PASSWORD: "${HOYODECRIMEN_BACKUP_PASSWORD}"
      HOYODECRIMEN_PASSWORD: "${HOYODECRIMEN_PASSWORD}"
    image: diegovalle/hoyodecrimen-postgis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - default
    volumes:
      - /pgdata_hy:/var/lib/postgresql/data
    ports:
      - 5405:5432
    restart: always
version: '3'
